#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'my-test-pkg-py','console_scripts','node1'
__requires__ = 'my-test-pkg-py'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('my-test-pkg-py', 'console_scripts', 'node1')()
    )
